name: ğŸ·ï¸ Check Labels on Issues

on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  check-labels-on-issues:
    uses: Automattic/dangermattic/.github/workflows/reusable-check-labels-on-issues.yml@trunk
    with:
      label-error-message: "Test custom error messsage"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
